job:
  description: animal2vec torch2 16 kHz 5 s lr1e-4 training until epoch 1 end

  environment:
    image: cr.ai.cloud.ru/aicloud-base-images/py3.10-torch2.2.2:0.0.40

  policy:
    allocation_name: alloc-airi-job-master-a100-sr006
    internet_access: true
    priority_class: medium

  resource:
    instance_type: a100.2gpu.16C.486G
    workers: 1

  script: /home/jovyan/iskhakov_anvar_local/cetaceans-filtering/jobs/animal2vec/train_16khz_5s_lr1e4_epoch1_torch2/run_job.sh
  type: binary
